name: my_recipes
description: "Enregistrez et organisez vos recettes préférées avec facilité !"

publish_to: "none"

version: 0.2.4+9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.8
  dynamic_color: ^1.7.0
  equatable: ^2.0.5
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  go_router: ^13.2.0
  logger: ^2.2.0
  lottie: ^3.1.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  image_path: "assets/images/menu_book.png"

  android: false # generate to Android Studio

  web:
    generate: true
    image_path: "assets/images/menu_book.png"
    background_color: "#201a1b"
    theme_color: "#fffbff"

flutter_native_splash:
  color: "#fffbff"
  image: assets/images/menu_book.png
  color_dark: "#201a1b"
