name: my_recipes
description: "Enregistrez et organisez vos recettes préférées avec facilité !"

publish_to: "none"

version: 0.4.0+19

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.17.2
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  flutter: { sdk: flutter }
  flutter_native_splash: ^2.4.0
  go_router: ^14.0.2
  logger: ^2.2.0
  lottie: ^3.1.0
  share_plus: ^9.0.0
  url_launcher: ^6.2.6
  uuid: ^4.4.0
  firebase_crashlytics: ^3.5.4
  firebase_performance: ^0.9.4+4
  fpdart: ^1.1.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  rxdart: ^0.27.7
  my_apps:
    git:
      url: git@github.com:Thematt69/my_apps.git
      ref: 0.0.6

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

flutter_launcher_icons:
  android: false # generate to Android Studio

  web:
    generate: true
    image_path: "assets/images/menu_book.png"
    theme_color: "#800020"

flutter_native_splash:
  color: "#FCF8F8"
  image: assets/images/menu_book.jpg
  color_dark: "#1C1C1C"
  image_dark: assets/images/menu_book_black.jpg
