name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Builds Android
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Configure Signature
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties
          echo "${{ secrets.RELEASE_KEYSTORE }}" > upload-keystore.encoded
          base64 -d -i upload-keystore.encoded > ./android/app/keystore.jks
      - name: Install Java 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "oracle"
          java-version: "17"
      - name: Install Flutter SDK ${{ vars.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true
          cache-key: flutter ${{ vars.FLUTTER_VERSION }}
      - name: Setup Android NDK r25c
        uses: nttld/setup-ndk@v1.4.2
        with:
          ndk-version: r25c
          local-cache: true
      - name: Configure Flutter
        run: |
          flutter config --no-cli-animations --no-analytics
          flutter pub get
      - name: Build AppBundle Release
        run: flutter build appbundle --release --no-tree-shake-icons  --dart-define="FIREBASE_WEB_KEY=${{ secrets.FIREBASE_WEB_KEY }}" --dart-define="FIREBASE_ANDROID_KEY=${{ secrets.FIREBASE_ANDROID_KEY }}" --dart-define="FRIDGE_FIREBASE_WEB_KEY=${{ secrets.FRIDGE_FIREBASE_WEB_KEY }}" --dart-define="FRIDGE_FIREBASE_ANDROID_KEY=${{ secrets.FRIDGE_FIREBASE_ANDROID_KEY }}" --obfuscate --split-debug-info=build/app/outputs/symbols --extra-gen-snapshot-options=--save-obfuscation-map=build/app/outputs/symbols/obfuscation_map.json
      - name: Push build to Releases
        uses: actions/upload-artifact@v4.3.1
        with:
          name: "build-release"
          path: |
            build/app/outputs/bundle/release/*.aab
            build/app/outputs/symbols
            build/app/intermediates/merged_native_libs/release/out/lib

  deploy:
    name: Deploy web
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Install Flutter SDK ${{ vars.FLUTTER_VERSION }}
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: ${{ vars.FLUTTER_VERSION }}
          cache: true
          cache-key: flutter ${{ vars.FLUTTER_VERSION }}
      - name: Configure Flutter
        run: |
          flutter config --no-cli-animations --no-analytics
          flutter pub get
      - name: Build Web Release
        run: flutter build web --release --no-tree-shake-icons --dart-define="FIREBASE_WEB_KEY=${{ secrets.FIREBASE_WEB_KEY }}" --dart-define="FIREBASE_ANDROID_KEY=${{ secrets.FIREBASE_ANDROID_KEY }}" --dart-define="FRIDGE_FIREBASE_WEB_KEY=${{ secrets.FRIDGE_FIREBASE_WEB_KEY }}" --dart-define="FRIDGE_FIREBASE_ANDROID_KEY=${{ secrets.FRIDGE_FIREBASE_ANDROID_KEY }}"
      - name: Sync files FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.matthieudevilliers.fr
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/web/
          server-dir: /recipe.matthieudevilliers.fr/
